### ISSUE TITLE
Issues caused by Brave and Edge using different userDataDir as Chrome (+ Fix)

### ISSUE THREAD

**Issue by tomkahn** [Xeo786/Rufaydium-Webdriver#18]
Hi Xeo786,

thank you for your work and effort on this. Rufaydium is a fine project and I'm impressed! Today I started using it to automate some tasks with Brave browser and ran into the following issues. They can be fixed quite easily and I wanted to let you and others know how.

Issues arise because Brave and Edge don't share the same userDataDir. Because of that if you don't change this variable but only the binary via `Chrome.capabilities.Setbinary("C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe")` when using Brave you cannot access your profiles. I fixed this by adding the following two lines to my script (before calling `Page := Chrome.NewSession()`):

```
Chrome.capabilities.RemoveArg("--user-data-dir=", match="nonexact")
Chrome.capabilities.addArg("--user-data-dir=C:\Users\" A_UserName "\AppData\Local\BraveSoftware\Brave-Browser\User Data")
```

But this can be easily fixed for all users by adding the following code to `setUserProfile` in Capabilites.ahk and calling it whenever .setBinary is used.

If user uses Chrome:
```
userDataDir := "C:/Users/" A_UserName "/AppData/Local/Google/Chrome/User Data"
```
If user uses Brave:
```
userDataDir := "C:/Users/" A_UserName "/AppData/Local/BraveSoftware/Brave-Browser/User Data/"
```
If user uses Chrome:
```
userDataDir := "C:/Users/" A_UserName "/AppData/Local/Microsoft/Edge/User Data"
```

Also if anybody runs into this issue (invalid argument: user data directory is already in use...):

![image](https://user-images.githubusercontent.com/38276038/183715852-2cb84588-cb2e-495d-892f-a1c0d0453ef5.png)

Don't worry, this is just because Brave doesn't like two different instances accessing the same user data directory at the same time. If you close your regular Brave instances and try again, everything will work fine. A more elegant solution might be to clone the user data directory temporarily as suggested [here](https://forum.katalon.com/t/user-data-directory-is-already-in-use/40266/2).

**Comment by Xeo786** [comment]
Made Changes to Capabilities to support User data profiles for Opera, Edge, and Brave. please test and confirm

**Comment by tomkahn** [comment]
If I do this:

```
#Include Rufaydium.ahk
Chrome := new Rufaydium("bravedriver")
```

I get the following error:

![image](https://user-images.githubusercontent.com/38276038/184007380-0caecc55-4922-4269-b30b-322e2bfe00f9.png)

Sometimes a zip file (called chromedriver-win32.zip I believe) appears in the folder for less than a second and disappears again directly afterwards.

It also tries to download if the chromedriver.exe already exists.

If I do this:

```
#Include Rufaydium.ahk
Chrome := new Rufaydium()
Chrome.capabilities.Setbinary("C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe")
Page := Chrome.NewSession()
Page.Navigate("brave.com")
```

it works, but doesn't use my default profile.

It is able to use my profile if I add the same lines as before:

#Include Rufaydium.ahk
Chrome := new Rufaydium()
Chrome.capabilities.Setbinary("C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe")
Chrome.capabilities.RemoveArg("--user-data-dir=", match="nonexact")
Chrome.capabilities.addArg("--user-data-dir=C:\Users\" A_UserName "\AppData\Local\BraveSoftware\Brave-Browser\User Data\")
Page := Chrome.NewSession()
Page.Navigate("brave.com")

**Comment by Xeo786** [comment]
I have added whole capabilities support for brave browser, no need to setbinary()
Try 
```Autohotkey
Brave := new Rufaydium("BraveDriver")
; here set user profile
Brave.url := Someurl
```
I am using cellphone, so please follow readme.md

**Comment by tomkahn** [comment]
Just did. Same issue:

![image](https://user-images.githubusercontent.com/38276038/184048295-bd1cfbc7-2d9a-4d1c-b006-a77a2fdd0370.png)

The first line already causes this issue:

`Brave := new Rufaydium("BraveDriver")`

**Comment by Xeo786** [comment]
I have fixed this and a few other issues about port

**Comment by tomkahn** [comment]
I tried this code from the latest readme:

```
#Include Rufaydium.ahk
Brave := new Rufaydium() ; Brave browser support chromedriver.exe
Session := Brave.NewSession("C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe")
Brave.Session() ; will always open new Brave session until we reset 
return
```

This causes this error:

![image](https://user-images.githubusercontent.com/38276038/184120654-395450a1-e5ef-4883-8dfd-42f6d52e2bcd.png)

If I modify the second line and add "BraveDriver" as argument:

```
#Include Rufaydium.ahk
Brave := new Rufaydium("BraveDriver"); Brave browser support chromedriver.exe
Session := Brave.NewSession("C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe")
Brave.Session() ; will always open new Brave session until we reset 
return
```

It still doesn't work. I get this error:
![image](https://user-images.githubusercontent.com/38276038/184121017-ed80c8be-4c24-4826-8eb2-6821a32880d5.png)

It would be great if you could give me a short script that I can run as a test that should work. The syntax seems to have changed a bit compared to the first version I tried.

**Comment by Xeo786** [comment]
Actually, I do not have brave on my PC at work.
the following code should work, Binary been set internally [see line 42](https://github.com/Xeo786/Rufaydium-Webdriver/blob/main/Rufaydium.ahk#L42), and its loading BraveCapabilities class which has its own setUserProfile method [see line 351](https://github.com/Xeo786/Rufaydium-Webdriver/blob/main/Capabilities.ahk#L351)
```autohotkey
#Include Rufaydium.ahk
Brave := new Rufaydium("BraveDriver") 
Brave.Capabilities.setUserProfile(profileName, userDataDir)
Brave.Session()
return```

**Comment by tomkahn** [comment]
Just tried your code. This code doesn't give me an error but it also doesn't run either brave or the chrome driver. (I replaced profileName and userDataDir with the correct values.)

It also seems to download the driver every time, even when the chromedriver.exe already exists.

**Comment by Xeo786** [comment]
I think I have to debug code on PC with brave, I am planning to do that later, would take a little time.

**Comment by tomkahn** [comment]
No worries, take your time.

If I may suggest something:

It would be great if the setUserProfile() function would be called automatically when you specify a driver other than Chrome (see the values provided in my [original post](https://github.com/Xeo786/Rufaydium-Webdriver/issues/18#issue-1333559860)), such that users don't have to do it explicitely unless they need it. In most cases people will just want to use the standard userDataDir for their browser as well as the default profile. So it would be great if this function only needed to be called when users want to use a different profile and/or a different userDataDir.

Is there a reason why you use NewSession() under Chrome but Session() under Brave? As well as Navigate() under Chrome and Brave.url = under Brave? Same commands for all browser would make things easier to understand as well.

**Comment by Xeo786** [comment]
There are security reasons why should not we run Driver Session with a user's profile,
Closing this issue ...!

**Comment by tomkahn** [comment]
Hi @Xeo786 thank you for looking into it. Can you link to a document that explains what exactly the issue is in this case?

**Comment by Xeo786** [comment]
I was to say user's profile which is already being accessed cannot be accessed using webdriver, so you need to close the browser that accessing it then try creating Webdriver session

**Comment by tomkahn** [comment]
Hi Xeo, I don't think that is related to the errors I described in my last posts because I knew about this already in my first post. I wrote:

>Also if anybody runs into this issue (invalid argument: user data directory is already in use...):
>image
>Don't worry, this is just because Brave doesn't like two different instances accessing the same user data directory at the same time. If you close your regular Brave instances and try again, everything will work fine.

So the errors I had were not related to this. At some point I can try the latest version again with Brave. Have a good weekend!
